try tfold

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,7 +24,7 @@ matrix:
     allow_failures:
     - php: nightly
 
-before_script:
+before_install:
     - |
         tfold () {
             local title=$1
@@ -36,12 +36,29 @@ before_script:
             echo -e "travis_fold:start:$fold"
             echo -e "travis_time:start:$id"
             echo -e "\\e[33;1m$title\\e[0m"
-            echo -e "HELLO"
+            bash -xc "$*" 2>&1
+            local ok=$?
             local end=$(date -u "+%s%N")
             echo -e "\\ntravis_time:end:$id:start=$start,finish=$end,duration=$(($end-$start))"
             echo -e "travis_fold:end:$fold"
         }
         export -f tfold
+
+install:
+    - |
+        run_tests() {
+            set -e
+
+            tfold a.1 \
+            "HELLO !"
+            tfold a.2 \
+            "ls -d tests/Domain/* | parallel --gnu --keep-order 'echo "Running {} tests"; phpdbg -qrr phpunit -c phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));'"
+            tfold a.3i \
+            "BYE !!!"
+        }
+        export -f run_tests
+
+before_script:
     - phpenv config-rm xdebug.ini || echo "Xdebug not available"
     # Add composer's global bin directory to the path
     # see: https://github.com/drush-ops/drush#install---composer
@@ -51,7 +68,4 @@ before_script:
     - composer install --no-dev --prefer-dist --ansi --no-interaction --no-suggest --no-progress --optimize-autoloader
 
 script:
-    - tfold a.1
-    - tfold a.2
-    - ls -d tests/Domain/* | parallel --gnu --keep-order 'echo "Running {} tests"; phpdbg -qrr phpunit -c phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));'
-    - tfold a.3
+    - (run_tests)
